version: '3.2'

services:
  back-end:
    image: backend
    build: ./back-end
    container_name: back-end
    restart: unless-stopped
    tty: true    
    networks:
      - backend-network
    volumes:
      - composer:/var/www/back-end/vendor      
      - ./back-end/:/var/www/back-end # Dev-Only
    environment:
      - JWT_SECRET=zalo
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=loans
      - DB_USERNAME=user
      - DB_PASSWORD=pass_user
  
 
  worker:
    image: worker
    build: ./python-worker
    container_name: worker
    restart: unless-stopped
    tty: true    
    networks:
      - worker-network
    volumes:
      - ./python-worker/:/app-worker/   
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=loans
      - DB_USERNAME=user
      - DB_PASSWORD=pass_user
      - REDIS_HOST=redis

  proxy: 
    image: nginx:1.21
    container_name: proxy
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:      
      - ./back-end/:/var/www/back-end    
      - ./proxy:/etc/nginx/conf.d/     
    depends_on:
      - back-end
    networks:
      - backend-network

  web-socket:
    image: web-socket
    container_name: web-socket
    build: ./web-socket
    restart: unless-stopped
    volumes:
      - ./web-socket/:/app
    tty: true
    environment:      
      - REDIS_HOST=redis
      - JWT_SECRET=zalo
    networks:
      - worker-network
      - backend-network
    

volumes:
  composer:

networks:
  backend-network:
    driver: bridge
  worker-network:
    driver: bridge