version: '3.2'

services:
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: loans
      MYSQL_ROOT_PASSWORD: pass_root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files      
    networks:
      - backend-network

volumes:
  dbdata:
    driver: local