version: '3.2'

services:
  back-end:
    image: backend
    build: ./back-end
    container_name: back-end
    restart: unless-stopped
    tty: true    
    networks:
      - backend-network
    volumes:
      - /var/www/back-end/vendor      
      - ./back-end/:/var/www/back-end # Dev-Only
  
  proxy: 
    image: nginx:1.21
    container_name: proxy
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:      
      - ./back-end/:/var/www/back-end    
      - ./proxy:/etc/nginx/conf.d/     
    depends_on:
      - back-end
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge