version: '3.2'

services:

  back-end:
    volumes:
      - composer:/var/www/back-end/vendor      
      - ./back-end/:/var/www/back-end # Dev-Only

  proxy:
    volumes:      
      - ./back-end/:/var/www/back-end    
      - ./proxy:/etc/nginx/conf.d/     

  worker:
    volumes:
      - ./python-worker:/home/app/app-worker
    depends_on:
      - db
      - redis

  web-socket:
    depends_on:
      - redis      
    volumes:
      - ./web-socket/:/app

  redis:
    image: redis:6.2.6
    command: redis-server --appendonly yes
    container_name: redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - worker-network 

  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-loans}
      MYSQL_ROOT_PASSWORD: pass_root
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-pass_user}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files      
    networks:
      - backend-network
      - worker-network

volumes:
  dbdata:
    driver: local
  composer:
    driver: local

networks:
  backend-network:
    driver: bridge
  worker-network:
    driver: bridge